#DEV Environment em YAML

server:
  port: 8085

app:
  message: This is the property file for the ${spring.application.name} specific to DEV Environment

spring:
  datasource:
  drive-class-name: org.h2.Driver
  url:idbc:h2: mem:db;DB_CLOSE_DELAY=-1
  username: sa
  password: sa
